# Generated by Django 5.2.8 on 2025-12-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('coat', '코트'), ('jacket', '자켓'), ('padding', '패딩'), ('mtm', '맨투맨'), ('hoodie', '후드티'), ('jeans', '청바지'), ('slacks', '슬랙스'), ('jogger', '조거팬츠'), ('shorts', '반바지'), ('hat', '모자'), ('bag', '가방'), ('belt', '벨트'), ('glasses', '안경'), ('sneakers', '운동화'), ('boots', '부츠'), ('sandals', '샌들'), ('loafers', '로퍼')], default='coat', max_length=20),
        ),
    ]
